# We require "sudo" since we're running a docker container.
# See: https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker

language: python

# This should match the version run by tox.
python:
  - "3.6"

install:
  - pip install codecov

script:
  # Run tox tests
  - ./compose.sh tox
      run
      -v $PWD:/tmp/workspace
      -e COVERAGE_FILE=/tmp/workspace/.coverage
      -e TOXINI_ARTEFACT_DIR=/tmp/workspace/build
      --rm
      tox
  - ./compose.sh tox down

  # Check that the production container builds and listens on port 8000
  - ./compose.sh production up -d
  - ./compose/wait-for-it.sh localhost:8000 -t 15
  - ./compose.sh production exec production_app ./manage.py migrate

  # The health-check endpoint should return a non-fail status.
  - curl --location --output /tmp/status --fail --silent --connect-timeout 2
      http://localhost:8000/status

after_success:
  - codecov

# From: https://docs.travis-ci.com/user/deployment/pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build/doc/
    email: automation@uis.cam.ac.uk
    name: Automation Bot
    on:
      branch: master
